import Head from "next/head";
import Navbar from "../components/Nabvar/Navbar";
import Tasks from "../components/Tasks/Tasks";

export default function Home() {
  return (
    <>
      <div class="application application-offset ready">
        <Head>
          <title>Admin Dashboard</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <Navbar />
        <div class="container-fluid container-application">
          <Tasks />
        </div>
      </div>
    </>
  );
}
